services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/loading2022/line-chatbot.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
# - type: web
#   name: line-bot-python-flask-with-handler
#   env: python
#   repo: https://github.com/loading2022/line-chatbot.git
#   buildCommand: pip install gunicorn -r requirements.txt
#   startCommand: gunicorn app_with_handler:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-flask-kitchensink
#   env: python
#   repo: https://github.com/loading2022/line-chatbot.git
#   buildCommand: pip install gunicorn -r requirements.txt
#   startCommand: gunicorn app:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-simple-server
#   env: python
#   repo: https://github.com/loading2022/line-chatbot.git
#   buildCommand: pip install -r requirements.txt
#   startCommand: python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-aiohttp
#   env: python
#   repo: https://github.com/loading2022/line-chatbot.git
#   buildCommand: pip install -r requirements.txt
#   startCommand: python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
